version: "3"
services:
  app:
    build: ./app
    privileged: true
    restart: always
    environment:
      - MYSQL_PASSWORD=stingray-coleslaw-overbill
      - ADMIN_TOKEN=TISC{1:3:3:7:l:3:4:k:1:n}
      - EMAIL=pasty-shrank-faction@celestial-stapling-captivate.org
      - PASSWORD=cloning-rising-amulet
      - BASE_URL=http://localhost:8000

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:8080

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=granite-numeric-canopener
      - MYSQL_DATABASE=palindrome
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    
  redis:
    image: redis
    restart: always
